version: "3.8"

services:

  app:
    image: infx-mapping-api
    build:
      context: .
      dockerfile: Dockerfile
#    env_file:
#      - .env
#    environment:
#      - FLASK_APP=app
    volumes:
      - './infx_mapping_api:/app/app:rw'
    ports:
      - 8000:8000
  

