version: "3.8"

services:

  app:
    image: infx-semantic-normalization-api
    build:
      context: .
      dockerfile: Dockerfile
#    env_file:
#      - .env
#    environment:
#      - FLASK_APP=app
    volumes:
      - './infx_semantic_normalization_api:/infx_semantic_normalization_api/app:rw'
    ports:
      - 8000:8000
  

